scripts/SREP/etcd-health-check/metadata.yaml, scripts/SREP/etcd-health-check/script.sh
Close [OSD-8444](https://issues.redhat.com/browse/OSD-8444)
=> Enable CEE to check etcd health

Dockerfile, scripts/CEE/registry-s3-bucket-size/metadata.yaml, scripts/CEE/registry-s3-bucket-size/script.sh
https://issues.redhat.com/browse/OSD-8686
Also fixed the original script from ops-sop here: https://github.com/openshift/ops-sop/pull/1563
=> [OSD-8686] Convert v4-registry-s3-size script to managed-script

Dockerfile, scripts/SREP/example/metadata.yaml, scripts/SREP/get-targets-down/metadata.yaml, scripts/SREP/get-targets-down/script.sh
Jira: [OSD-8685](https://issues.redhat.com/browse/OSD-8685)
=> Add get-targets-down script

scripts/CEE/get-kafka-instance-state/metadata.yaml
[MGDSTRM-6827](https://issues.redhat.com/browse/MGDSTRM-6827)
=> Add endpointslice list permission

scripts/CEE/check-tech-preview-features/README.md, scripts/CEE/check-tech-preview-features/metadata.yml, scripts/CEE/check-tech-preview-features/script.sh
Resolves: [OSD-9511](https://issues.redhat.com/browse/OSD-9511)
=> OSD-9511: Enable CEE to identify if customer is running any tech preview feature

scripts/SREP/elasticsearch-status/metadata.yaml, scripts/SREP/elasticsearch-status/script.sh
Converting elastic search status script to managed-scripts
=> OSD-8682 Converting elastic search status script to managed-scripts

scripts/CEE/get-rhosak-operators/get-rhosak-operators.sh, scripts/CEE/get-rhosak-operators/metadata.yaml
Adding a script that uses oc adm inspect to get resources from RHOSAK operators.
=> Adding get rhosak operator script

Dockerfile, scripts/CSSRE/lib/py/command.py, scripts/CSSRE/lib/py/exceptions.py, scripts/CSSRE/lib/py/logger.py, scripts/CSSRE/lib/py/script.py
What we want to achieve:
1. to add common reusable lib in `managed-scripts/CSSRE`
2. required package install - tabulate in the managed-scripts `Dockerfile`
this is related to [CSSRE-1853](https://issues.redhat.com/browse/CSSRE-1853): to add a script to diagnose node-restarts
=> CSSRE-1943: add lib folder in CSSRE dir and package install in Dockerfile

scripts/CSSRE/OWNERS
As an SRE I want someone from my team specifically to review my PR in the managed backplane script repo (openshift/managed-scripts) so that I can make sure that I'm conforming to our conventions or patterns.
cc @pepedocs
=> CSSRE-1942: add owners in CSSRE directory

scripts/SREP/mg-log-extractor/metadata.yaml, scripts/SREP/mg-log-extractor/script.sh, scripts/SREP/mg-log-ls/metadata.yaml, scripts/SREP/mg-log-ls/script.sh
Creates two commands:
ocm backplane mg-log-ls # shows list of must-gathers in the hive s3 bucket
ocm backplane mg-log-extractor <s3-file-name> <clustername>-must-gather.tar.gz # extracts a must-gather from the hive s3 bucket
=> Add commands to list and get must-gathers from hive s3 buckets

Dockerfile
Install the python openshift-client which also requires an upgrade of pip to do so.
=> Install python openshift-client

scripts/CEE/get-kafka-instance-state/metadata.yaml
Reverting rbac clean up for get kafka instance script from this pr https://github.com/openshift/managed-scripts/pull/65/files as permission errors are happening
=> Reverting permission changes

scripts/CEE/pcap-collector/README.md, scripts/CEE/pcap-collector/metadata.yaml, scripts/CEE/pcap-collector/script.sh
https://issues.redhat.com/browse/OSD-11526
Replacing https://github.com/openshift/ops-sop/blob/master/v4/utils/pcap-collector.sh which doesn't work with backplane into a managedjob
=> pcap collector job

scripts/CEE/pcap-collector/script.sh
Some error handling and resolving https://github.com/openshift/managed-scripts/pull/70#discussion_r881111043
=> Add some error handling

scripts/CEE/pcap-collector/metadata.yaml, scripts/CEE/pcap-collector/script.sh
_RFE_ : Parameterize NetworkType related packet capture.
=> Add capability for additional network plugin related packet capture

scripts/CEE/describe-kafka-transaction/metadata.yaml, scripts/CEE/get-kafka-instance-state/metadata.yaml, scripts/CSSRE/get-kafka-topics/get-kafka-topics.py, scripts/CSSRE/get-kafka-topics/metadata.yaml, scripts/CSSRE/lib/py/exceptions.py, scripts/CSSRE/lib/py/kafka.py, scripts/CSSRE/under-min-isr-partitions/metadata.yaml, scripts/CSSRE/under-replicated-partitions/metadata.yaml
Making this as a draft PR to ask some questions on the work I'm doing to refactor these scripts to use services instead of statefulsets, for the work on migrating to using strimzipodsets :)
=> Update scripts to use services instead of statefulsets to support strimzipodsets

scripts/SREP/replace-master/metadata.yaml, scripts/SREP/replace-master/script.sh
Add a script to help replacing the master machine. Input the machine name of the master, and it will delete that master machine and create a new one with same configuration.
=> OSD-12042 add a script to replace master

template/README.md, template/metadata.yaml, template/script.sh
This PR adds a standard bash template to the managed scripts repository.
<hr>
Resolves: [OSD-12093](https://issues.redhat.com/browse/OSD-12093)
=> Add a standard bash template to managed scripts

scripts/CEE/get-rhoc-connector-info/get-rhoc-connector-info.sh
Sending collected information about a connector to stdout using tar command, so that data can be downloaded to local machine for analysis.
=> [MGDCTRS-1665] sending collected information to stdout using tar

scripts/SREP/delete-olm-operator/metadata.yaml
Signed-off-by: Ankit Kurmi <akurmi@redhat.com>
=> [MTSRE-870] creating backplane permissions to perform full blown OLM dance

scripts/CEE/cluster-health-check/README.md, scripts/CEE/cluster-health-check/metadata.yaml, scripts/CEE/cluster-health-check/run-oc-hc.sh
Create a managed-script that downloads the oc-hc module and runs it for automating a variety of health checks
=> Added cluster-health-check script

Dockerfile
build and add the hypershift binary to the base image, so that must gather can consume it directly
=> [OSD-17593] add hypershift binary to base image

scripts/SREP/etcd-complete-health-check/README.md, scripts/SREP/etcd-complete-health-check/metadata.yaml, scripts/SREP/etcd-complete-health-check/script.sh
This PR adds a managed script for complete ETCD health check
=> OSD-17592: Added script for etcd complete health check

Dockerfile
Adding yq binary to the managed script docker image 
Search yaml files based on criteria
=> OSD-17959: Add yq binary into managed-scripts container image

scripts/LPSRE/get-kafka-topics/README.md, scripts/LPSRE/get-kafka-topics/get-kafka-topics.py, scripts/LPSRE/get-node-restarts/README.md, scripts/LPSRE/get-node-restarts/script.py, scripts/LPSRE/rolling-restart-brokers/README.md, scripts/LPSRE/under-min-isr-partitions/README.md, scripts/LPSRE/under-min-isr-partitions/under-min-isr-partitions.py, scripts/LPSRE/under-replicated-partitions/README.md, scripts/LPSRE/under-replicated-partitions/under-replicated-partitions.py
Since PR 126, files from LPSRE were still pointing to the previous directory CSSRE. The files were updated to the correct path now.
=> osd-18602-updated-files

scripts/CEE/hs-must-gather/script.sh
This PR resolves the issue [OSD-18647](https://issues.redhat.com/browse/OSD-18647)
Instead of deleting all YAML files, it only deletes those that contain a 
- Secret
- SecretList
- .data[] that contains "CERTIFICATE"
=> OSD-18647 - Only deletes Secrets, SecretList and Certificates

scripts/SREP/retry-failed-pruning-cronjob/script.sh
Fix `oc get job` command to get jobs from a particular cronjob.
=> Fix Cronjob Command

.github/PULL_REQUEST_TEMPLATE.md
Adding a template that will help add convey more information about the pr
=> OSD-19418: Add pull request template for managedscript

scripts/CEE/drain-reboot-nodes/README.md, scripts/CEE/drain-reboot-nodes/metadata.yaml, scripts/CEE/drain-reboot-nodes/script.sh
Feature
This PR is necessary to add a new managed script for draining/rebooting worker nodes.
_Resolves #_ https://issues.redhat.com/browse/OSD-19453
=> OSD-19453: Drain reboot worker nodes

scripts/SREP/retry-failed-pruning-cronjob/script.sh
_bug_
script will not fail when no failed pruning jobs are found
_Resolves #_
=> Remove return 1 when no failed jobs are found..

scripts/SREP/node-drain-reboot/README.md, scripts/SREP/node-drain-reboot/metadata.yaml, scripts/SREP/node-drain-reboot/script.sh
_feature_
It will help drain and reboot nodes without elevation thus reducing the no of compliance tickets generated due to draining
_Resolves_ #[OSD-19603](https://issues.redhat.com/browse/OSD-19603)
=> OSD-19603: Script to drain and reboot node without elevation

OWNERS
=> Add more reviewers and approvers

Makefile, hack/app_sre_build_deploy.sh
bug
Fix the issue related to https://issues.redhat.com/browse/ASIC-542
=> Use container engine to push instead of skopeo

scripts/CEE/pcap-collector/README.md, scripts/CEE/pcap-collector/metadata.yaml, scripts/CEE/pcap-collector/script.sh
_feature_
It'll help add interface as a parameter in pcap-collecter managed-scripts and help fetch traffic on that network interface
_Resolves #[OSD-21752](https://issues.redhat.com/browse/OSD-21752)_
=> OSD-21752: Add interface parameter for pcap-collector managed-script

Dockerfile
=> update the golang to latest version

OWNERS
=> cleanup: update owner

scripts/LPSRE/increasing-observability-operator-pvc-size/metadata.yaml, scripts/LPSRE/increasing-observability-operator-pvc-size/script.sh
feature
Fix: https://issues.redhat.com/browse/MTSRE-1769
This needs to be executed using lPSRE group permissions that are assigned to associates
=> migrate dp-012-increasing-observability-operator-pvc-size.md to managed scripts

README.md, scripts/CEE/kubelet-restart/README.md, scripts/CEE/kubelet-restart/metadata.yaml
bug
The name in the metadata must be the same as the directory name.
_Resolves #_
=> Fix the name in metadata

.gitignore, scripts/SREP/ocpbugs-33377-workaround/README.md, scripts/SREP/ocpbugs-33377-workaround/metadata.yaml, scripts/SREP/ocpbugs-33377-workaround/script.sh
feature
Adds a new managed script for management clusters that will allow it to remediate OCPBUGS-33377
=> Add script for OCPBUGS-33377 workaround

Dockerfile
_feature_
Make the binaries in the image are up to date
_Resolves #[OSD-19695](https://issues.redhat.com//browse/OSD-19695)_
=> [OSD-19695] make sure the binaries are up to date

scripts/SREP/update-upgrade-policy-state/README.md, scripts/SREP/update-upgrade-policy-state/metadata.yaml, scripts/SREP/update-upgrade-policy-state/script.sh
_bug_
Fixes the update-upgrade-policy-state script by fetching the cluster-id using `oc` command instead of `ocm`
_Resolves #_
=> Fix update-upgrade-policy-state script

scripts/CEE/list-alerts/metadata.yaml
bug
Fixes permissions in the list alerts script
_Resolves #_
=> Fix permissions on alerts script

OWNERS
=> Add SRE-P Orange to owners

scripts/CEE/hive-data-collection/README.md, scripts/CEE/hive-data-collection/metadata.yaml, scripts/CEE/hive-data-collection/script.sh
Merge the new managed-script to production
This PR is intended to add a new script responsible for collecting data from Hive clusters in order to troubleshoot/debug cluster provisioning delays.
_Resolves #_ https://issues.redhat.com/browse/OSD-17974
As the Hive clusters are in Production, the script has been tested locally connected to a Hive cluster
=> Managed Script for Hive Data Collection

Dockerfile, Makefile
Add osdctl to Docker image for managed scripts
https://issues.redhat.com/browse/SREP-861
_Resolves #_
=> Add osdctl to dockerfile

scripts/troubleshooting/hs-manifest-gather/README.md, scripts/troubleshooting/hs-manifest-gather/metadata.yaml, scripts/troubleshooting/hs-manifest-gather/script.sh
_(feature)_
Assisted-by: Cursor
The main purpose of this work is to enable the MCS team to gather manifests/CRs by themselves for HCP clusters.
https://issues.redhat.com/browse/SREP-1328
This has been tested on staging cluster and output/log has been attached to JIRA card.
=> Hypershift manifests/CRs gather script
