scripts/SREP/node-logs/metadata.yaml, scripts/SREP/node-logs/script.sh
Allow CEE to read node-logs.
The permission `nodes/proxy` is too wide, so we use a wrapper managed-script to allow them to read journal log on that node only.
=> OSD-8555 allow CEE to read node-logs

scripts/SREP/get-targets-down/metadata.yaml, scripts/SREP/get-targets-down/script.sh
* In some cases, the route domain name cannot be resolved
jira: [OSD-8685](https://issues.redhat.com/browse/OSD-8685)
=> get-targets-down: Use internal prometheus domain name

scripts/managed-services/get-kafka-instance-state/get-kafka-instance-state.sh, scripts/managed-services/get-kafka-instance-state/metadata.yaml
This PR is to add a script and accompanying metadata file that can be ran against a single Kafka instance and will then return a tar stream of all the logs/events/CRs in the instance.
=> Add get Kafka instance state script

scripts/CEE/get-kafka-instance-state/metadata.yaml
The script requires these RBAC permissions to lookup the resource name (`oc get ...`).
=> Add RBAC for managedkafka and kafka resources

scripts/CEE/get-kafka-instance-state/metadata.yaml
statefulset and pod permissions were absent, this caused the commands that query kafka state to fail.
=> Add missing permissions to kafka-instances script

scripts/CEE/get-kafka-instance-state/get-kafka-instance-state.sh, scripts/CEE/get-kafka-instance-state/metadata.yaml
This is a PR to make an edit to the get-kafka-instance-state script to allow optional since/since-time flags to be specified.
=> Add optional since/since-time flags as environment variables

scripts/SREP/cluster-operator-status/README.md, scripts/SREP/cluster-operator-status/metadata.yaml, scripts/SREP/cluster-operator-status/script.sh
Refs: [OSD-8688](https://issues.redhat.com/browse/OSD-8688)
This PR adds a `cluster-operator-status` managed script script to gather data on degraded or unavailable cluster operators.
It can optionally target a specific cluster operator via the `CLUSTER_OPERATOR` parameter.
Successfully tested via `ocm backplane testjob create`. (An easy scenario to test against that quickly simulates cluster operator failures is to cordon and drain a master node.)
=> OSD-8688 Add cluster-operator-status script

.gitignore, scripts/CSSRE/get-node-restarts/README.md, scripts/CSSRE/get-node-restarts/metadata.yaml, scripts/CSSRE/get-node-restarts/script.py
What we want to achieve:
1. to add get-node-restart script in `managed-scripts/CSSRE`
2. the `get-node-restart` script will check for node restarted within given duration and lists out pods associated with the node
this is related to https://issues.redhat.com/browse/CSSRE-1853: to add a script to diagnose node restarts
testing in staging cluster - done
=> CSSRE-1853: add get-node-restart script

scripts/CEE/get-rhosak-operators/metadata.yaml
`get-rhosak-operators` name in the metadata file does not mach the directory name. This causes a 404 error if you try to run or describe the script using the name provided by `backplane scripts list`.
```
$ ocm backplane script describe CEE/get-RHOSAK-operators
ERRO[0000] error from backplane: 
Status Code: 404
Message: Script not found
```
=> Rename get-rhosak-operators to match directory

scripts/CSSRE/get-kafka-topics/README.md, scripts/CSSRE/get-kafka-topics/get-kafka-topics.sh, scripts/CSSRE/get-kafka-topics/metadata.yaml
Added a script that runs the `kafka-topics.sh` scripts that is built into Kafka pods. It's used to get details of Kafka topics and partitions and also filter by under replicated, under min ISR or offline partitions.
=> Added scripts to get kafka topics

scripts/CEE/get-kafka-instance-state/metadata.yaml, scripts/CEE/get-rhosak-operators/metadata.yaml
fixing the rbac permissions in the get kafka instance script to remove rbac as the default cluster read permissions is enough  https://issues.redhat.com/browse/MGDSTRM-8074
=> updating rbac cluster roles

scripts/SREP/delete-olm-operator/script.sh
This corrects a bug in the `delete-olm-operator` managed script.
Currently this script does not remove the `last-applied-configuration` annotation from the `subscription`, `catalogsource` and `operatorgroup` resources that it saves, deletes and recreates.
This means that when the script recreates the resources, the Hive `clustersync` will no longer be able to successfully clustersync them. In the case of a `catalogsource` this is quite bad as it means the cluster will no longer be receiving operator updates.
The fix ensures that the `last-applied-configuration` annotation is removed.
I have tested it in a staging cluster to ensure it still works.
=> Fix clustersync-breaking bug in delete-olm-operator

scripts/CSSRE/lib/py/kafka.py, scripts/CSSRE/under-min-isr-partitions/README.md, scripts/CSSRE/under-min-isr-partitions/metadata.yaml, scripts/CSSRE/under-min-isr-partitions/under-min-isr-partitions.py, scripts/CSSRE/under-replicated-partitions/under-replicated-partitions.py
This is a managed script for the under min ISR alert in Kafka. It's pretty much a copy paste of the [under replicated partition managed script](https://github.com/openshift/managed-scripts/tree/main/scripts/CSSRE/under-replicated-partitions) as the kafka.py class already has the logic to handle partitions that are under minimum ISR.
=> Added managed script for under min isr partitions

scripts/CEE/list-alerts/README.md, scripts/CEE/list-alerts/script.sh
[MGDSTRM-8276](https://issues.redhat.com/browse/MGDSTRM-8276)
Update the script to list alerts from any/all Prometheus hosts by providing the namespace/s containing the Prometheus host. Defaults to checking the `openshift-monitoring` Prometheus if no namespace(s) are provided. The README contains instructions on how to use the script. It can tested when logged in via `oc` by exporting the `NAMESPACE` list: `export NAMESPACE="<list of namespaces>"`.
=> List alerts for multiple Prometheus hosts

scripts/CEE/pcap-collector/metadata.yaml
_Error_ 
```
sh-4.4# oc get network cluster -o jsonpath='{.spec.networkType}'
Error from server (Forbidden): networks.config.openshift.io "cluster" is forbidden: User "system:serviceaccount:openshift-backplane-managed-scripts:openshift-job-r2krl" cannot get resource "networks" in API group "config.openshift.io" at the cluster scope
```
- This PR will fix the resource name typo
=> Fix resource name typo

scripts/CEE/describe-kafka-transaction/describe-kafka-transaction.sh, scripts/CEE/get-kafka-instance-state/get-kafka-instance-state.sh, scripts/CEE/get-kafka-instance-state/metadata.yaml
This is a draft pull request to get feedback and test some changes.
Changing the oc exec commands to use services instead of statefulsets. Strimzi is moving away from statefulsets, so we want this script to be able to support both approaches.
=> Change oc exec commands to use services instead of statefulsets

scripts/CSSRE/lib/py/kafka.py
There is a potential for an injection attack in the `kafka.py` script. Using a list of commands instead of `cmd.split()` will fix it. 
The issue was raised here: https://github.com/openshift/managed-scripts/issues/84
JIRA: [CSSRE-2200](https://issues.redhat.com/browse/CSSRE-2200)
I tested the changes by creating strimzi and kafka instances locally on CRC and running the script - no issues encountered.
=> Prevent potential injection attack

hack/metadata.schema.json
Manage Scripts require a label as part of their metadata. This property enables the consumers to differentiate between scripts that are meant for only specific scenarios as opposed to scripts that are meant for general usage.
This PR adds label property to Managed Scripts metadata.
=> OSD-13035 - Add label support for script metadata

scripts/SREP/example/metadata.yaml
Resolves: [OSD-13036](https://issues.redhat.com//browse/OSD-13036)
This PR updates the example script to demonstrate how to use labels on managed scripts. The intention is to provide an example so that other contributors can follow and add labels appropriately to their own scripts after testing.
=> OSD-13036 - Add cluster compatibility labels to example script

scripts/CEE/pcap-collector/metadata.yaml, scripts/CEE/pcap-collector/script.sh
[OSD-12040](https://issues.redhat.com/browse/OSD-12040)
[OSD-12258](https://issues.redhat.com/browse/OSD-12258)
This pull request extends the managed script `pcap-collector` to upload files of arbitrary size to the support case SFTP folder, similar to the [must gather operator](https://github.com/openshift/must-gather-operator). It also adds the ability to add `pcap_filters` (like `not tcp` or `icmp`) as a flag to the script, allowing the user to drill down on traffic they want to sniff.
It takes much inspiration from how to use existing [must-gathers](https://source.redhat.com/groups/public/openshiftplatformsre/wiki/how_to_use_the_must_gather_operator). The basic process is to upload a secret with your username, sftp token, internal user status, and caseid as the parameters, and then …
=> Extend pcap-collector script to upload to SFTP and add pcap filters flag

scripts/SREP/get-targets-down/metadata.yaml, scripts/SREP/get-targets-down/script.sh
`oc sa get-token` is deprecated. In 4.11+ there's no secret associated with SA. We will need to use `oc create token <SA>` to get a token instead.
Tested changes in 4.10, 4.11 and 4.12, work as expected.
=> OSD-15321 fix get sa token

scripts/CEE/check-tech-preview-features/metadata.yaml, scripts/CEE/describe-kafka-transaction/metadata.yaml, scripts/CEE/etcd-health-check/metadata.yaml, scripts/CEE/get-kafka-instance-state/metadata.yaml, scripts/CEE/get-rhoc-connector-info/metadata.yaml, scripts/CEE/get-rhosak-operators/metadata.yaml, scripts/CEE/list-alerts/metadata.yaml, scripts/CSSRE/get-kafka-topics/metadata.yaml, scripts/CSSRE/get-node-restarts/metadata.yaml, scripts/CSSRE/rolling-restart-brokers/metadata.yaml, scripts/CSSRE/under-min-isr-partitions/metadata.yaml, scripts/CSSRE/under-replicated-partitions/metadata.yaml, scripts/SREP/cluster-operator-status/metadata.yaml, scripts/SREP/describe-nodes/metadata.yaml, scripts/SREP/elasticsearch-status/metadata.yaml, scripts/SREP/example/metadata.yaml, scripts/SREP/get-targets-down/metadata.yaml, scripts/SREP/node-logs/metadata.yaml, scripts/SREP/tsdb-status/metadata.yaml
lpsre groups is not updated to the allowedGroups in the managed-backplane-scripts after the merge of CSSRE and MTSRE teams,
updated now
=> added LPSRE to allowedGroups

scripts/CEE/get-rhoc-connector-info/get-rhoc-connector-info.sh
Fixing [MGDCTRS-2112](https://issues.redhat.com//browse/MGDCTRS-2112). stderr output needs to be redirected to a file and not go into the pod's log.
=> [MGDCTRS-2112] - redirecting stderr to file in get-rhoc-connector-info script

scripts/examples/lib-sourcer/metadata.yaml, scripts/examples/lib-sourcer/script.sh, scripts/lib/examples/lib.sh
Rewrite of https://github.com/openshift/managed-scripts/pull/106. 
Adds the ability to `source` a bash library from anywhere within the `scripts` directory.
If a script is in `/scripts/SREP/script.sh`, and the library is also in `/scripts/lib/lib.sh`, it must be sourced like so in `script.sh`:
`source /managed-scripts/lib/lib.sh`. This is due to how the managed scripts are bundled in the `Dockerfile`. 
On staging/production, these will be built in. This behaviour is emulated in backplane test jobs by inlining the library scripts.
=> Managed job library support

Dockerfile, scripts/CEE/cluster-health-check/run-oc-hc.sh
- v0.1.2 enforced the user to be cluster-admin, which causes the following error when running the managed script:
```
$ ocm backplane testjob logs openshift-job-dev-8jkwn -f
[Info] Using default kubeconfig: /root/.kube/config
[Info] kubeconfig invalid, tryin to use current-context
Checking if user has cluster-admin privileges...
[Error] Something went wrong:   [Error] User is not a cluster-admin. 
```
v0.1.3 removes that check
- Enabled debug mode for error messages
=> Update CEE/cluster-health-check to use oc-hc v0.1.3

OWNERS
Not sure how this was missed, adding myself (@supreeth7) to the approvers' list of managed-scripts as one of the maintainers.
This PR also removes the maintainers list as it isn't relevant for GitHub (only GitLab).
=> Add supreeth7 as an approver

README.md
As a part of [OSD-17611](https://issues.redhat.com//browse/OSD-17611), this PR intends to add information on Managed Scripts .
=> OSD-17611 : Adding information on Managed Scripts release cycles

scripts/CEE/hs-must-gather/README.md, scripts/CEE/hs-must-gather/metadata.yaml, scripts/CEE/hs-must-gather/script.sh
This PR adds the RBAC rules and commands that enabled hs-must-gather to do a full hypershift dump.
Resolves: 
* [OSD-17639](https://issues.redhat.com/browse/OSD-17639)
* [OSD-17850](https://issues.redhat.com/browse/OSD-17850)
Sample run:
```
$ ocm backplane testjob create -f -p CLUSTER_NAME=taf-mg    
Test job openshift-job-dev-ttlhp created successfully
Run "ocm backplane testjob get openshift-job-dev-ttlhp" for details
Run "ocm backplane testjob logs openshift-job-dev-ttlhp" for job logs	
TestId: openshift-job-dev-ttlhp
$ ocm backplane testjob logs openshift-job-dev-ttlhp
Executing hypershift dump on ocm-staging-25gfjutppguvfur1923uq33ub5nmortn for cluster taf-mg
2023-08-10T15:14:29Z    INFO    Dumping guestcluster    {"target": "taf-mg/hostedcluster-taf-mg"}
2023-08-10T15:16:49Z …
```
=> OSD-17639 - Add full hypershift dump

scripts/CEE/cordon-uncordon-nodes/README.md, scripts/CEE/cordon-uncordon-nodes/metadata.yaml, scripts/CEE/cordon-uncordon-nodes/script.sh
Reasons for writing this script:
- MCS has received in the past many cases where the customer asks us to cordon/uncordon a worker node, and since we don't have privileges to do it we need to engage SRE via OHSS.
- Additionally, sometimes customers ask us to do that in a specific timeframe, which can not be guaranteed by SRE but would be accommodated in the MCS schedule.
I have tested this script on the staging environment
=> cordon-uncordon-nodes script

Dockerfile
We are adding the package check-jsonschema to this Dockerfile in order to have the package available on the existing managed-scripts image. This will be used for the json schema validation.
After this PR, we will raise a new one in order to update the schema validation script.
=> osd-17784: addind check-jsonschema to Dockerfile

hack/schema_validation.sh
Changed the command for the schema validation using the new image.
And removed the 'success' message as it is already provided by the command output.
=> osd-17784: changing schema validation script

hack/metadata.schema.json, scripts/LPSRE/rolling-restart-brokers/metadata.yaml
After testing the json files with the new 'check-jsonschema' package towards the existing jsonschema, it has been identified some issues with the structure of the jsonschema and also with the metadata.yaml of rolling-restart-brokers script. This commit is to fix both files.
=> osd-17784: fixing json schema and a metadata.yaml

scripts/CEE/hs-must-gather/README.md, scripts/CEE/hs-must-gather/script.sh
According to the [OSD-17641](https://issues.redhat.com/browse/OSD-17641) spike, some sensitive files need to be removed from the hypershift dump which contains:
- All Secrets
- certificates in the configMap
Working Jira Task: https://issues.redhat.com/browse/OSD-17960
- Remove the above files list from tarball from the existing hypershift dump
- Compress the files with the same format with the new list of files
=> Removing the sensitive files from the hypershift dump

Dockerfile, scripts/lib/sftp_upload/lib.sh
https://access.redhat.com/articles/5594481
We can allow a managed-script to upload files using the unauthenticated way, so that we don't need to handle any secret in the script.
=> Add SFTP upload function

scripts/CEE/hs-must-gather/README.md, scripts/CEE/hs-must-gather/script.sh
This PR:
- adds a function to upload the compressed tarball to SFTP. `upload_tarball()`  
- wraps the hypershift dump logic into a function. `collect_must_gather()`  
- uses the HostCluster name in `hypershift dump cluster --name`.
Test steps:
- Login to a management cluster.
- Create a testjob with a HCP cluster id.
```
$ ocm-backplane testjob create -p CLUSTER_ID=xxxxxxx
ocm.stg backplane testjob logs openshift-job-dev-clqj9
[long long logs]
Compressed hypershift dump is saved as /root/xxxxxxx
/20230919_xxxxxxx_dump.tar.gz
Uploaded file /root/xxxxxxx/20230919_xxxxxxx_dump.tar.gz to sftp.access.redhat.com, Anonymous username: iMMsiJbN, filename: 20230919_xxxxxxx_dump.tar.gz
For more information about SFTP: https://access.redhat.com/articles/5594481
```
=> OSD-17674 Upload the must gather tarball to SFTP

Makefile, README.md, hack/schema_validation.sh, hack/yamltojson.py
- Improved the hack/schema_validation.sh to run the validation also to single/multiple scripts if needed.
- Now, the script is intended to run a single container which reads a variable with all scripts to test. This optimized a lot the process.
- The check-jsonschema package also permits to run the validation on YAML files. So, the script was adapted to run the validation directly instead of converting them first to JSON. This also optimized the process a bit more.
- For the new feature, it was necessary to change the Makefile to consider the arguments.
- The README.md file was updated to present the 2 available validation methods.
=> osd-18431: schema_validation.sh improvements

scripts/CEE/hs-must-gather/metadata.yaml, scripts/CEE/hs-must-gather/script.sh, scripts/lib/sftp_upload/lib.sh
This PR adds some minor improvements to the `hs-must-gather` script.
1. Adds a DUMP_GUEST_CLUSTER parameter to optionally include / exclude guest cluster must gather
2. Separates control plane and data plane logs for ease of consumption
3. Renders the SFTP username in lowercase to make it easy to built the SFTP `get` command for download
=> Minor improvements over hyperhift must gather script

Dockerfile
Updating Python to release 3.11, and consequently check-jsonschema to 0.26.3.
Installing Python 3.11, it is required to install pip as well.
=> osd-18432: updating python release

scripts/SREP/retry-failed-pruning-cronjob/README.md, scripts/SREP/retry-failed-pruning-cronjob/metadata.yaml, scripts/SREP/retry-failed-pruning-cronjob/script.sh
This script is for the alert Pruning Cronjob Error. Here it will detect and delete the failed jobs that are running in the `openshift-sre-pruning` namespace and causing this error, deleting will help recreate new jobs and possibly resolve the alert, and if not SREs can start investigating and find the root cause.
=> OSD-19295: Managed Script to Re-run jobs that fail in openshift-sre-pruning namespace

scripts/SREP/retry-failed-pruning-cronjob/metadata.yaml
A small fix for the managed script `retry-failed-pruning-cronjob`. The name was different from the subdir.
=> Fix Error for Managed Script to Re-run jobs that fail in openshift-sre-pruning namespace

hack/metadata.schema.json
This PR adds the schema update necessary to use clusterVersion validation feature for managed-scripts.
Resolves: [OSD-18414](https://issues.redhat.com//browse/OSD-18414)
=> OSD-18414 - Update metadata schema to use clusterVersion

scripts/SREP/retry-failed-pruning-cronjob/script.sh
This PR Fixed a command which lists all the failed jobs in `retry-failed-pruning-cronjob` script
=> Fix failed job error

scripts/SREP/retry-failed-pruning-cronjob/README.md, scripts/SREP/retry-failed-pruning-cronjob/script.sh
Failed job command is restructured which will help detect jobs that are failed because the pod takes forever to complete.
=> Restructure Failed job command

scripts/CEE/list-alerts/script.sh
bug
The `get-token` command is deprecated as an SA token for the prometheus-k8s service account may not exist.
_Resolves #_
=> Update from deprecated get-token command

scripts/SREP/get-pull-secret-email/README.md, scripts/SREP/get-pull-secret-email/metadata.yaml, scripts/SREP/get-pull-secret-email/script.sh
Feature
In some cases, SRE need to validate if the email in the pull secret matches the record in OCM.
Instead of pulling down the how secret file, we can use this script to only get the info needed for validation.
Part of [OSD-19605](https://issues.redhat.com//browse/OSD-19605)
The test result looks like this:
```
ocm backplane testjob logs openshift-job-dev-wnrbj 
siwu@redhat.com
```
It can be run on both classic OSD and Hypershift clusters.
=> OSD-19605 a script to extract email from pull secret

scripts/SREP/cluster-operator-status/script.sh
_cleanup_
Use -o wide when getting pods for the cluster-operator-status job.
This will help diagnose node specific problems quicker because we will know which node each pod is running on.
_Resolves #_
=> Use -o wide when getting pods for the cluster-operator-status job

scripts/SREP/infra-node-resize/README.md, scripts/SREP/infra-node-resize/metadata.yaml, scripts/SREP/infra-node-resize/script.sh
_feature_
It will help automate infra-node resize and without any elevation. SRE just needs to pass the Internal Cluster ID, hive name and the desired instance size.
_Resolves_ #[OSD-19604](https://issues.redhat.com/browse/OSD-19604)
This script runs in hive, so to test it in a staging cluster you need to create a hive namespace, install the hive operator, and then add the machinepools.
=> OSD-19604: Script to automate infranode resize without elevation

template/README.md
_(cleanup)_
The link to google bash styleguide is broken. I replaced http://google-styleguide.googlecode.com/svn/trunk/shell.xml with https://google.github.io/styleguide/shellguide.html
=> Fixed broken link for google styles

scripts/CEE/restart-dns-default/README.md, scripts/CEE/restart-dns-default/metadata.yaml, scripts/CEE/restart-dns-default/script.sh
This script will trigger a rollout of daemonset, controlling dns default pods. Such action might be required when a customer is not able to perform it themself due to not having enough permissions etc, but dns-default pods need to be restarted.
We have a use case scenarios where a customer is required to restart dns default e.g. after applying a dns forwarding (if this script is considered as a valid then it can be applied to apiserver etc which will reduce the number of requests for SRE) pods and can't do it to multiple reasons (e. g. not having enough permissions, not being able to log in or not having enough expertise). Having this script will let MCS to perform this on behalf of the customer. This script will be run by the CRU member only.
This is a second attempt as was requested in …
=> Restart dns default pods

Dockerfile, Makefile
Version bumps to UBI and yq
Pins UBI to a specific version instead of using latest, and updates the yq version to get the latest CVE patches. 
https://issues.redhat.com/browse/OSD-22358
=> Use specific UBI version, and update yq version

scripts/CEE/collect-verbose-ca-logs/README.md, scripts/CEE/collect-verbose-ca-logs/metadata.yaml, scripts/CEE/collect-verbose-ca-logs/script.sh
A feature addition for MCS team that will enable them to collect and filter verbose cluster autoscaler logs.
The script will be responsible for collection and filtering verbose logs from cluster autoscaler pod. We get a lot of cases where the customer reports issues with autoscaling nodes in the cluster (for ex: underutilized nodes are not scaling down). With current logs verbosity, it is not possible to find out the exact reason for why the nodes were not scaling down/up. On the other hand, setting permanent high value for logVerbosity aggressively uses the storage. The script will update the verbosity, collect the verbose logs for 6 minutes and reset the logVerbosity value. The script will also filter the collected based on node names.
Additionally, we will be using this script to …
=> Feature cluster autoscaler logs

Dockerfile, Makefile, hack/schema_validation.sh
bug
Docker build throws the following errors. 
```
oc: /lib64/libc.so.6: version `GLIBC_2.33' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.34' not found (required by oc)
oc: /lib64/libc.so.6: version `GLIBC_2.32' not found (required by oc)
```
_Resolves #_
https://issues.redhat.com/browse/OSD-24608
=> OSD-24608 : fixed docker file build issue and SElinux container execute issues 

Makefile, scripts/CEE/check-tech-preview-features/README.md, scripts/CEE/check-tech-preview-features/script.sh, scripts/CEE/get-events/script.sh, scripts/CEE/hs-must-gather/script.sh, scripts/CEE/kubelet-restart/script.sh, scripts/CEE/list-alerts/script.sh, scripts/CEE/worker-node-operations/script.sh, scripts/SREP/describe-nodes/metadata.yaml, scripts/SREP/describe-nodes/script.sh, scripts/SREP/infra-node-resize/script.sh, scripts/SREP/manage-silence/script.sh, scripts/SREP/mg-log-extractor/script.sh, scripts/SREP/mg-log-ls/script.sh, scripts/SREP/retry-failed-pruning-cronjob/script.sh, scripts/SREP/update-upgrade-policy-state/script.sh, scripts/examples/lib-sourcer/script.sh, scripts/lib/sftp_upload/lib.sh
_bug_
It will update the scripts as the shell check points out new errors. We've switched to EPEL8 as Centos7/RHEL7 reached EOL a month ago and they moved EPEL7 to archive [https://dl.fedoraproject.org/pub/epel/](https://dl.fedoraproject.org/pub/epel/) [https://dl.fedoraproject.org/pub/archive/epel/](https://dl.fedoraproject.org/pub/archive/epel/).
_Resolves_ #[OSD-24941](https://issues.redhat.com/browse/OSD-24941)
=> [OSD-24941] Update make file to use EPEL8 and fix all the shell check errors

scripts/lib/sftp_upload/lib.sh
_bug_
It will create a temporary file when the sftp upload function is called, and the SSH known hosts file will be set up within this temporary directory. This avoids permission issues by using a directory that the script can write to.
_Resolves_ #[OSD-23707](https://issues.redhat.com/browse/OSD-23707)
=> OSD-23707: Fix the sftp_upload() to make it able to upload the file to SFTP

scripts/CEE/collect-verbose-ca-logs/script.sh
Modifying the message that gets displayed if the script is unable to retrieve logVebosity value. The descriptive message will help the user to verify if the autoscaling is properly enabled. Additionally, increasing the sleep time from 5 seconds to 10 seconds to address interim issues in pod name discrepancy.
Script improvement
The PR has following changes:
- Modifying the message that gets displayed if the script is unable to retrieve logVebosity value.
- Increasing the sleep time from 5 seconds to 10 seconds to address interim issues in pod name discrepancy.
=> Update script.sh for managedjob CEE/collect-verbose-ca-logs

scripts/CEE/hs-must-gather/README.md, scripts/CEE/hs-must-gather/script.sh
bug
The latest MG container has permission issue with PWD=root.
```
ERROR	Cannot create directory	{"directory": "/root/xxxxxxx/network_logs", "error": "mkdir /root/xxxxxxx: permission denied"}
```
This PR changes to use `/tmp/` to store the dump data.
Also, as debug handler is disabled in the production environment, it couldn't dump guest cluster logs.
```
ERROR	Failed to dump guest cluster	{"error": "cannot forward kube apiserver port: error upgrading connection: unable to upgrade connection: Debug endpoints are disabled., output: "}
```
This PR adds a note in the README to suggest to use `osdctl` instead.
https://issues.redhat.com/browse/OSD-25772
Validated in a staging cluster by `ocm backplane testjob` and the /tmp/ directory works for staging.
=> OSD-25772 fix permission issue and add note for debug handler

scripts/CEE/check-tech-preview-features/metadata.yaml, scripts/CEE/cluster-health-check/metadata.yaml, scripts/CEE/collect-verbose-ca-logs/metadata.yaml, scripts/CEE/delete-worker-node/metadata.yaml, scripts/CEE/describe-kafka-transaction/metadata.yaml, scripts/CEE/etcd-health-check/metadata.yaml, scripts/CEE/get-events/metadata.yaml, scripts/CEE/get-kafka-instance-state/metadata.yaml, scripts/CEE/get-rhoc-connector-info/metadata.yaml, scripts/CEE/get-rhosak-operators/metadata.yaml, scripts/CEE/hs-must-gather/metadata.yaml, scripts/CEE/kubelet-restart/metadata.yaml, scripts/CEE/list-alerts/metadata.yaml, scripts/CEE/pcap-collector/metadata.yaml, scripts/CEE/registry-s3-bucket-size/metadata.yaml, scripts/CEE/restart-dns-default/metadata.yaml, scripts/CEE/worker-node-operations/metadata.yaml, scripts/SREP/cluster-operator-status/metadata.yaml, scripts/SREP/describe-nodes/metadata.yaml, scripts/SREP/elasticsearch-status/metadata.yaml, scripts/SREP/etcd-complete-health-check/metadata.yaml, scripts/SREP/example/metadata.yaml, scripts/SREP/get-pull-secret-email/metadata.yaml, scripts/SREP/get-targets-down/metadata.yaml, scripts/SREP/node-logs/metadata.yaml, scripts/SREP/tsdb-status/metadata.yaml
Feature/Cleanup
Adds the TierTwoSupport user role to the Backplane Managed Scripts
Also seems to be lots of `yq` formatting since I piped this all through `yq` using:
```
for folder in `find scripts -type d`; do echo "Dir: $folder"; if stat "$folder/metadata.yaml" >&/dev/null; then; if yq '.allowedGroups' "$folder/metadata.yaml" | grep CEE; then yq e -i '.allowedGroups += [ "TierTwoSupport" ]' "$folder/metadata.yaml" >&/dev/null; echo "  Updated"; fi; else; echo "  No CEE access"; fi; done
```
_Resolves [OSD-26528](https://issues.redhat.com/browse/OSD-26528)_
=> adds mcs tier two role to BPMS

CONTRIBUTING.md
documentation
_(bug/feature/cleanup/documentation)_
This PR adds a document on guidelines and best practices for contributing to managed-scripts
[OSD-19235](https://issues.redhat.com//browse/OSD-19235).
This PR is an extension/take over from Abhishek Sheth's PR https://github.com/ASheth1/managed-scripts/blob/main/CONTRIBUTING.md 
I have taken over as his secondment is over.
_Resolves #_
[OSD-19235](https://issues.redhat.com//browse/OSD-19235)
=> OSD-19235:Adding Contributing.md

scripts/CEE/get-haproxy-config/README.md, scripts/CEE/get-haproxy-config/metadata.yaml, scripts/CEE/get-haproxy-config/script.sh
This adds a new managed script to print the contents of the `/var/lib/haproxy/conf/haproxy.config` file from one of the default router pods.
This helps troubleshooting Ingress connection issues such as misconfigured routes or mismatched routes/endpoints.
[OSD-26547](https://issues.redhat.com/browse/OSD-26547)
I have tested this in a staging cluster.
=> Get haproxy config

Dockerfile
_(bug/feature/cleanup/documentation)_
bug
This PR updates the Dockerfile to use `rm -f `when removing cleanup files `(/root/anaconda*, /root/original-ks.cfg)`. This prevents build failures when the files are not present in the image.
=> fix(Dockerfile): use 'rm -f' to avoid errors when cleanup files are missing

scripts/networking/network-verify/README.md, scripts/networking/network-verify/metadata.yaml, scripts/networking/network-verify/script.sh
feature
https://issues.redhat.com/browse/SREP-861
_Resolves #_
Allows MCS to use osdctl network-verify in pod mode with a service account
```
$ ocm backplane testjob create -c $CLUSTER_ID
Test job openshift-job-dev-gd6mf created successfully
Run "ocm backplane testjob get openshift-job-dev-gd6mf" for details
Run "ocm backplane testjob logs openshift-job-dev-gd6mf" for job logs
```
TestId: openshift-job-dev-gd6mf
```
$ ocm backplane testjob logs openshift-job-dev-gd6mf
INFO: Starting osdctl network verification script
INFO: Running in pod with ServiceAccount token
INFO: Downloading latest osdctl binary...
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
0     0    0     0    0     0      0      0 --:--:-- --:--:-- …
```
=> SREP-861: osdctl network verify-egress in managed-scripts
